# Prometheus configuration for Telemetra MVP
# Minimal setup for development monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'telemetra-dev'
    environment: 'development'

# Scrape configurations
scrape_configs:
  # Backend FastAPI metrics
  - job_name: 'telemetra-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Kafka JMX Exporter metrics
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-jmx-exporter:9404']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Spark Master metrics
  - job_name: 'spark-master'
    static_configs:
      - targets: ['spark-master:8080']
    metrics_path: '/metrics/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Spark Worker metrics
  - job_name: 'spark-worker'
    static_configs:
      - targets: ['spark-worker:8081']
    metrics_path: '/metrics/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Redis Exporter metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    scrape_timeout: 10s

  # PostgreSQL Exporter metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s
    scrape_timeout: 10s
