# Grafana datasource provisioning for Prometheus
# Automatically configures Prometheus as a datasource on startup

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: prometheus
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
